### ISSUE TITLE
configure: error: AsciiDoc not found, not able to generate the man page.

### ISSUE THREAD

**Issue by chenliangfei** [vasi/pixz#100]
[root@localhost pixz-master]# ./autogen.sh 
configure.ac:47: installing './config.guess'
configure.ac:47: installing './config.sub'
configure.ac:11: installing './install-sh'
configure.ac:11: installing './missing'
src/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
[root@localhost pixz-master]# ./config
config.guess  config.sub    configure     
[root@localhost pixz-master]# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking for a2x... no
configure: error: AsciiDoc not found, not able to generate the man page.
[root@localhost pixz-master]# 

Can I help you?

**Comment by vasi** [comment]
You can also pass `--without-manpage` to skip manpage generation so you don't need asciidoc. The option is mentioned in `configure --help`.

As you noticed, you'll need LZMA as well, see the list of dependencies: https://github.com/vasi/pixz#dependencies

If you share what distro you're on, and what version, I'd be happy to help you figure out the right commands to get the dependencies.
