### ISSUE TITLE
Clarify README section on differences with xz

### ISSUE THREAD

**Issue by bearrito** [vasi/pixz#115]
I'm not critiquing the decision, I'm trying to understand if there is a technical hurdle lurking in the background.

Right now we use `xz` as part of our A/B partition update for firmware like systems. As part of how the system works, we need to stream to stdout.  The performance of pixz is impressive so we'd like to use it...

**Comment by vasi** [comment]
Stdout is totally supported! I can do `cat SOMEFILE | pixz | wc -c` and I get totally reasonable results. Is there some situation where stdout is not working for you?

**Comment by bearrito** [comment]
@vasi Maybe I'm misinterpreting this statement, my fault if so.

```
pixz does not support the command line option -c or --stdout
```

Namely we have something like this 
```
xz -d -c $IMAGE_PATH | sudo dd skip=$SKIP_BLOCKS of=$PARTITION 
```

**Comment by vasi** [comment]
Ah, so your problem is we don't have the exact same arguments as `xz`. But you can still do the same operation, just worded a bit different:

`xz -d < $IMAGE_PATH | sudo dd skip=$SKIP_BLOCKS of=$PARTITION`

Probably we should edit the README.md to be clearer!

**Comment by bearrito** [comment]
Thanks for the fast response. Get some sleep (or not) ! 
I'll try that tomorrow!

**Comment by vasi** [comment]
Updated the readme!
