### ISSUE TITLE
option -V doesn't work

### ISSUE THREAD

**Issue by Jun-T** [vasi/pixz#117]
'pixz -V' gives 'illegal option --V' instead of printing the version number.

In the following line:
https://github.com/vasi/pixz/blob/eda054a382aff179f91a87c544fbed42633d997b/src/pixz.c#L77
the lower case 'v' in the optstring "dcxli:o:tkvhp:..." existed even before the commit 631c916068f6c14a006888427cc45e71bd2ca444 but has never been used?
If 'v' is not used then just replace it with the upper ccase 'V'.

**Comment by vasi** [comment]
Ooh nice catch! We should fix this.

The lower-case `-v` actually works implicitly, it'll pick the default case and run `usage()`. I don't think it's technically necessary to include it in the option string for that though.

**Comment by vasi** [comment]
Fixed on master.
