### ISSUE TITLE
Extracting multiple files at once

### ISSUE THREAD

**Issue by isarandi** [vasi/pixz#118]
Thanks for this work! I'm wondering if I'm missing something, but it seems one can only provide one path as -x, ie a file to be extracted, or more precisely a path prefix, and then all files with that path prefix get extracted. However, if one needs more precise control of what to extract, it seems the extractions need to be done file-by-file, which is wasteful with many small neighboring files as the same blocks will get decompressed over and over.

Ideally one could supply the paths for example through stdin, with a null byte separator or newline separator, or as multiple -x arguments, like "-x path1 -x path2", though the latter would have a quite restrictive limit due to argument count limits. Here I would accept if the order must match the order in the file, as this would allow starting immediately before consuming the entire list of wanted paths.

**Comment by vasi** [comment]
If I understand what you're asking, I think this already works. Eg, on a tarball containing the pixz sources, I can extract three separate files in one pass, with:

`pixz -x -i test.tar.pxz src/read.c src/cpu.c README.md | tar xv`

Is that what you're trying to accomplish?

**Comment by isarandi** [comment]
Yes, thanks, that's great. I think the man page could be clearer about this, it looked like only one path can be passed.
