### ISSUE TITLE
Static Compiling for Scientific Linux 6.5

### ISSUE THREAD

**Issue by lasso012** [vasi/pixz#32]
I'd like to compile pixz for use on a Scientific Linux 6.5 OS. It seems that the xz development library is too old to work with the current version of pixz. I get the below error:

``` bash
$ git clone https://github.com/vasi/pixz.git
$ cd pixz
$ make
gcc  -g -O0 -std=gnu99 -Wall -Wno-unknown-pragmas -DPIXZ_VERSION='"1.0.2"'  -c -o pixz.o pixz.c
gcc  -g -O0 -std=gnu99 -Wall -Wno-unknown-pragmas -DPIXZ_VERSION='"1.0.2"'  -c -o common.o common.c
common.c: In function ‘find_file_index’:
common.c:119: error: ‘lzma_index_iter’ undeclared (first use in this function)
common.c:119: error: (Each undeclared identifier is reported only once
common.c:119: error: for each function it appears in.)
common.c:119: error: expected ‘;’ before ‘iter’
common.c:120: warning: implicit declaration of function ‘lzma_index_iter_init’
common.c:120: error: ‘iter’ undeclared (first use in this function)
common.c:122: warning: implicit declaration of function ‘lzma_index_iter_locate’
common.c: In function ‘next_index’:
common.c:329: warning: implicit declaration of function ‘lzma_index_stream_flags’
common.c:331: warning: implicit declaration of function ‘lzma_index_stream_padding’
common.c: In function ‘decode_index’:
common.c:344: error: too few arguments to function ‘lzma_index_cat’
make: *** [common.o] Error 1
```

I have the following versions of the xz-devel and libarchive-devel packages:

``` bash
$ yum info xz-devel
Loaded plugins: refresh-packagekit, security
Installed Packages
Name        : xz-devel
Arch        : x86_64
Version     : 4.999.9
Release     : 0.3.beta.20091007git.el6
Size        : 145 k
Repo        : installed
From repo   : sl
Summary     : Devel libraries & headers for liblzma
URL         : http://tukaani.org/xz/
License     : LGPLv2+
Description : Devel libraries and headers for liblzma.


$ yum info libarchive-devel
Loaded plugins: refresh-packagekit, security
Installed Packages
Name        : libarchive-devel
Arch        : x86_64
Version     : 2.8.3
Release     : 4.el6_2
Size        : 97 k
Repo        : installed
From repo   : sl
Summary     : Development files for libarchive
URL         : http://code.google.com/p/libarchive/
License     : BSD
Description : The libarchive-devel package contains libraries and header files for
            : developing applications that use libarchive.
```

Is it possible to grab the [xz](http://tukaani.org/xz/) and [libarchive](http://www.libarchive.org/) source (maybe a specific compatible version) and statically compile pixz?

I found a reference to static compiling pixz here: http://lists.opensuse.org/archive/opensuse-commit/2013-12/msg01104.html. Maybe I can do something similar.

**Comment by voltagex** [comment]
Following these steps, I still couldn't get a static pixz binary

`./src/pixz: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=9d4c4a920ceb1d4b0707257578d63b55d98efe32, not stripped`

pixz was built with

`make CFLAGS="-I$MYPREFIX/include/" LIBPREFIX=$MYPREFIX LIBADD="-lpthread -Wl,-Bstatic -llzma -larchive -Wl,-Bdynamic -lm"`

**Comment by wookietreiber** [comment]
@voltagex I assume, you are still on an older version. Please check out the [latest release](https://github.com/vasi/pixz/releases) which builds the project using autotools.

To link statically, you first need to have all the dependencies as static libraries, i.e. `libarchive.a` and `liblzma.a`. Then, you can build with:

```
export LDFLAGS="-static"
./configure
make
```

This should statically link `pixz`.

**Comment by cicku** [comment]
`/usr/bin/ld: cannot find -lgcc_s`

Something wrong with shared object linker

**Comment by cicku** [comment]
`,-Bstatic -llzma -larchive`

You were trying to link shared libraries to static objects, but not static libraries at all.

**Comment by tomck** [comment]
This should be retitled RHEL6, because it affects CentOS 6 too:

xz (XZ Utils) 4.999.9beta
liblzma 4.999.9beta

I'm also having issues with the static compiling, even with export LDFLAGS="-static", I have the .a files in the location that I'm setting for LIBARCHIVE_LIBS and also copied in the folder I'm building from, so I'm not sure what I'm missing.

**Comment by andreasstieger** [comment]
Yes, [in this package](https://build.opensuse.org/package/view_file/home:AndreasStieger:branches:Archiving/pixz/pixz.spec?expand=1) I use the following:

    export LIBARCHIVE_LIBS="-Wl,-Bstatic -larchive -Wl,-Bdynamic,-lbz2"
    export LZMA_LIBS="-Wl,-Bstatic -llzma -Wl,-Bdynamic"

I also provide static libraries for libarchive and lzma in the same project as build dependencies, in versions required for pixz to work. These are not available on the stock target distribution, and static linking prevents version incompatibilities.

A platform not having the required build dependencies is not really a bug in pixz. So if we take my package as a demonstrator on how to build pixz on Scientific Linux 6.5, the issue can be closed.
