### ISSUE TITLE
Compressing directly from tar and specifying compression level?

### ISSUE THREAD

**Issue by baldoam** [vasi/pixz#33]
This is a documentation question.  I'm posting it here as this seems to serve as a support forum of sorts for pixz.  

How would one compress directly instream from tar, while specifying the compression level?

I would like to do something like this analogous operation with pxz:
"nice -19 tar Oc foobar_directory | nice -19 pxz -9  -cv - > foobar.tar.xz"

Given the current documentation for pixz it isn't clear how to specify the compression level while doing this:
(tar -Ipixz -cf foo.tpxz foo_directory           # Create a tarball using pixz for multi-core compression)

- With xz this can be solved by setting the environment variable to maximum compression as default (eg "export XZ_OPT=-9e") but it isn't clear to me if similar variables exist for pixz that I can set.

- Or maybe is there a way to pass the -9 to pixz through the "tar -Ipixz" that I'm unaware of?

Thanks in advance for any suggestions!

**Comment by vasi** [comment]
You can just pipe through pixz. The syntax "tar -Ifoo -f bar.tar -c ..." is just shorthand for "tar -c ... | foo > bar.tar".

So in your case, you'd do ```nice -19 tar Oc foobar_directory | nic -19 pixz -9 > foobar.tar.xz```
