### ISSUE TITLE
Contributors wanted!

### ISSUE THREAD

**Issue by voltagex** [vasi/pixz#36]
Just checking in - pixz works well for me.

**Comment by vasi** [comment]
I'm still around, but I don't have a lot of time to look at things, I've been really busy with work and family.

Unfortunately when I wrote pixz, it was more of an experiment than a well-planned project. I never expected other people to find it so useful! It uses fairly unclean code, eg: global variables all about, so it definitely needs some spit and polish—if anybody wants to try refactoring it a bit, I'd welcome that :)

**Comment by wookietreiber** [comment]
In the form of pull requests or as a full access contributor?

**Comment by vasi** [comment]
I'd be happy to give you a commit bit! Same goes for anybody else who has C experience. Someone who's just learning programming should probably start with a PR, though to be honest they probably couldn't do much worse than my code on pixz :P

**Comment by vasi** [comment]
I also have a branch sitting around somewhere with a partial refactoring, the goal of which was to allow pixz to work on gzip as well as xz format. I don't think I ever pushed it :( I'll see if I can find it, it might make a good starting point.

**Comment by wookietreiber** [comment]
Thanks for adding me, I'll do what I can.

**Comment by wookietreiber** [comment]
I am going to start by providing all changes I make as pull requests, even though I may merge these directly / instantly. This way, they can be discussed separately and certain issues that may occur can be ironed out.

**Comment by justinmayer** [comment]
Hey Dave. Would you consider adding me as a contributor as well? I've been a long-time Pixz user and fan, and I'd like to contribute from the perspective of testing, packaging, and documentation. I think I've done a fairly decent job at that on the [Pelican project](https://github.com/getpelican/pelican).  (^_^) 

Moreover, I'd like to contribute by helping with testing on Mac OS X prior to release, in order to ensure proper functionality on that platform.

Does that sound okay with you?

**Comment by vasi** [comment]
You're in :)

**Comment by justinmayer** [comment]
Thanks. You rock!

**Comment by wookietreiber** [comment]
Welcome!

**Comment by cicku** [comment]
I've found that clonezilla is using this. Packaging clonezilla is impossible due to non-free code. But [packaging pixz into Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1260911) is possible. If you add [me](https://github.com/cicku), appreciated then. :hammer:

**Comment by goblin** [comment]
Hi guys, I'd like to poke around a bit, maybe have a try at fixing #13 and/or #60, and I have a question: have you found any good documentation on xz (aka liblzma)? I'm having particular trouble finding anything about indices...
