### ISSUE TITLE
Build instructions mention non-existent `configure` script

### ISSUE THREAD

**Issue by justinmayer** [vasi/pixz#46]
The build instructions list `./configure` as the first step after downloading the release tarball, but the 1.0.3 release tarball does not contain a `configure` script.

(I'm in the process of submitting v1.0.3 to [Homebrew](https://github.com/Homebrew/homebrew), but I can't do that until I can reliably determine the proper installation steps for Mac OS X.)

Might someone point me in the right direction?

**Comment by cicku** [comment]
homebrew might use the wrong tarball? Release tarballs contain configure scripts, whereas the source tarballs don't contain. You need to manually run `autoreconf`.

**Comment by wookietreiber** [comment]
I have added the proper release tarballs to the [release page](https://github.com/vasi/pixz/releases), i.e. you should not use the *source code* tarballs, but the ones called `pixz-<version>.*`.

**Comment by justinmayer** [comment]
Thanks for the proper tarballs, Christian. After doing some testing on Mac OS X 10.10, I noticed that some of the changes in 1.0.3 required some modifications to the Homebrew formula. I made what I believe are the appropriate adjustments and have submitted a [pull request for 1.0.3](https://github.com/Homebrew/homebrew/pull/43707) to the Homebrew repository.

**Comment by wookietreiber** [comment]
@justinmayer Is `autoconf` really required? As far as I know, it should not be, because the `configure` script is already generated in the release tarball, and that is what `autoconf` does, generate `configure`.

**Comment by justinmayer** [comment]
You are correct. I added that back before the tarball had been fixed to include the `configure` script. Will update the pull request accordingly.
