### ISSUE TITLE
1.0.3 tarball not on SourceForge

### ISSUE THREAD

**Issue by ryandesign** [vasi/pixz#48]
It looks like pixz 1.0.3 was released, but its tarball was not uploaded to [SourceForge](http://sourceforge.net/projects/pixz/files/) where the pixz github project says the file should be.

**Comment by wookietreiber** [comment]
Please use the downloads at the release page: https://github.com/vasi/pixz/releases/tag/v1.0.3

I have just added the ready to use release tarballs with the prepared configure script to that page.

**Comment by wookietreiber** [comment]
@vasi do you want to drop releases on SourceForge, because GitHub can do it all?

**Comment by vasi** [comment]
Yeah, I think it's ok to drop SF. I think I only added it because at a certain time GitHub was deprecating releases.

I seem to recall that the debian/watch file for pixz points at SF, so we should make sure the Debian maintainer of pixz becomes aware of the new release.

**Comment by cicku** [comment]
SF sucks now. Tons of ads everywhere.

**Comment by wookietreiber** [comment]
@vasi do you have the email or GitHub account name of the debian maintainer?

**Comment by wookietreiber** [comment]
@vasi I am assigning this issue to you, because at the moment, you are the only one with access to the SF project.

**Comment by vasi** [comment]
Sent an email to the debian maintainer, David Bremner.

**Comment by ryandesign** [comment]
> Yeah, I think it's ok to drop SF. I think I only added it because at a certain time GitHub was deprecating releases.

github [deprecated the downloads feature](https://github.com/blog/1302-goodbye-uploads), then later [introduced the releases feature](https://github.com/blog/1547-release-your-software).

> I seem to recall that the debian/watch file for pixz points at SF, so we should make sure the Debian maintainer of pixz becomes aware of the new release.

Also make sure you remove the reference to files being at SourceForge from the top of the [project page](https://github.com/vasi/pixz).

**Comment by vasi** [comment]
Ok, removed the link to sourceforge. Also modified the sourceforge page to say that people should come to github.

**Comment by ryandesign** [comment]
> I have just added the ready to use release tarballs with the prepared configure script to that page.

Thanks. pixz has been updated to 1.0.3 in MacPorts.

**Comment by wookietreiber** [comment]
There also had been a reference in the man page to the download page at SF. I just removed it.
