### ISSUE TITLE
htole64 / le64toh on old glibc

### ISSUE THREAD

**Issue by andreasstieger** [vasi/pixz#52]
I have been using and providing [production rpms for CentOS / RHEL 5-7](http://download.opensuse.org/repositories/home:/AndreasStieger:/branches:/Archiving/) for a while. On 5 <del>and 6</del>, glibc is too old and it does not certain macros used in `src/endian.c`. I am patching in the following:

`# if __BYTE_ORDER == __LITTLE_ENDIAN`
`#  define htole64(x) (x)`
`#  define le64toh(x) (x)`
`# else`
`#  define htole64(x) __bswap_64 (x)`
`#  define le64toh(x) __bswap_64 (x)`
`# endif`

Use autoconf magic `AC_CHECK_DECLS` and conditionally define the above if not found as a macro or function in the target environment.

**Comment by wookietreiber** [comment]
Do you know which glibc version introduced both `htole64` and `le64toh`? We should apply these defines only for glibc version lesser than the one introducing these.

**Comment by wookietreiber** [comment]
Apparently, they are introduced in glibc 2.9. I think, the best way to address this is to check for both of these functions in `configure` and if they do not exist, define them ourselves.

**Comment by cicku** [comment]
Being as a person dealing with RHEL for several years, I'd say RHEL6 ships GLIBC

**Comment by andreasstieger** [comment]
As a correction to the original report, this affects CentOS 5 and RHEL 5 which have glibc-2.5, not 6. So yes this is a portability issue for glibc < 2.9.

**Comment by wookietreiber** [comment]
@andreasstieger would you please test [this patch](https://github.com/wookietreiber/pixz/commit/5d831e6d1b4f0fb62504307aeea2c062e783357e.patch) on both RHEL 5 and RHEL 6 (alternative to the patch, you can checkout the endian-conversion-checks branch on my fork)?

**Comment by andreasstieger** [comment]
https://github.com/wookietreiber/pixz/commit/5d831e6d1b4f0fb62504307aeea2c062e783357e works as intended on all affected targets, does not break others and would fix this issue.

**Comment by wookietreiber** [comment]
Great, @andreasstieger thanks for reporting back. I am going to merge and cut a new release.

**Comment by wookietreiber** [comment]
Done, new release is up.
