### ISSUE TITLE
release early / often, git branching model, CONTRIBUTING.md, (semantic) versioning

### ISSUE THREAD

**Issue by wookietreiber** [vasi/pixz#54]
You may have realized that I have pushed the last few releases quite fast and each included only a single hotfix. I think like release early and release often.

To support this workflow better, I would like to push for a specific git branching model, [this one](http://nvie.com/posts/a-successful-git-branching-model/) is a good starting point. There are some other models out there as well as refinements to the abovementioned one but this should be a good starting point for a branching model. I would also put this information in a `CONTRIBUTING.md` file in the repository, e.g. that new features must be contributed to the develop branch (see model description). Contributors will see a like to that file if they start to submit a PR (see also [here](https://github.com/blog/1184-contributing-guidelines)), so they will know about these contribution guidelines.

With the hotfix and release early and release often mindset, I would also like to bring in [semantic versioning](http://semver.org/), i.e. hotfixes increase patch version level, new features minor version level, incompatible changes major version number, etc. (read at link for more information). Example: if we bring in more command line options, e.g. for #19 we should increase minor version number, if we change or remove some command line option, we should increase major version number. (Actually, thinking about it, v1.0.3 should have been 1.1.0 ;) you see what I mean.)

I would like to get your opinion on these matters, especially from @vasi. If you have any questions about the topics above, feel free to ask. These topics are all obvious to me but might not to you, so if I left something out which should have been explained or reasoned about better, let me know.

**Comment by vasi** [comment]
I think semantic versioning would be a reasonable idea.

A more complex branching model might be reasonable, but I think will only be necessary once the pace of development and number of contributors is higher. At the moment, I think it might just discourage contribution? You are welcome to try whatever branching technique you like for your own code, of course :)

**Comment by wookietreiber** [comment]
I do not think it will discourage contribution. For PRs, contributors only need to base their PRs on the develop branch instead of the master branch, because the master branch contains only tagged, production ready releases. IIRC if you set the default branch at GitHub to develop instead of master, even this will be done automatically whenever you are creating a new PR. So the added complexity is generally rather low.

**Comment by justinmayer** [comment]
Are there problems with how Pixz releases are currently handled that would be solved by a more complex branching model? If not, I'm just wondering whether this might fall in the "premature optimization" category.

**Comment by andreasstieger** [comment]
As a distribution package maintainer, semantic versions are good, maintain(ed|able) releases are even better.

As for the development model.. don't think a project is only viable if features are added. For a really good parallel compressor, there is only so much you can do. Don't make it brew coffee.

**Comment by cicku** [comment]
C'mon, please don't remove elder releases!

**Comment by cicku** [comment]
Ignore my previous comment here

**Comment by wookietreiber** [comment]
Closing this for now.
