### ISSUE TITLE
feature request: support indices other than tar

### ISSUE THREAD

**Issue by goblin** [vasi/pixz#60]
It would be nice to be able to supply a list of positions in the decompressed file to which index entries would be created. This would allow indexing things other than tar (for instance wikimedia dump .xml files).
I see this as an option such as `--indices=<filepos.txt>` that would read byte positions from file filepos.txt. Maybe some way to name the positions too. Then during extraction you'd also indicate from which byte position (or position name) you want the extraction to start.

**Comment by vasi** [comment]
I'm not sure exactly what this means, it seems pretty far out there. You can totally use liblzma to do this without adding it to pixz.
