### ISSUE TITLE
Feature Request - compatible "-c" / pipe output 

### ISSUE THREAD

**Issue by ceinmart** [vasi/pixz#63]
Hi, 

I'm trying replace my scripts which use pigz to pixz , but lot of them I need to use the "-c" option, which means redirect the output to pipe ... 
Unfortunately this isn't supported by pixz and make much more difficult to handle bigs files with it ... 
I've try use "-o -"  which is common for certains GNU commands to redirect to output , but not work.

Simplifying , the command which I need to work  is something like this : 
`$ cat dummy.file | pixz -c > dummy.file.xz `
(please , this is very simple example of how need to work , but I need use it in this way over much more complexes situations)

**Comment by wookietreiber** [comment]
What you are describing already works. If there are no command line arguments, pixz automatically writes to STDOUT. There is a `-c` option, but it is silently ignored. This has been added in version 1.0.3, see #40.

Thus, both of the following are the same:

```
cat file | pixz    > foo.xz
cat file | pixz -c > bar.xz

file foo.xz bar.xz
md5sum foo.xz bar.xz
```

Both files should report as *XZ compressed data* and have the same md5.
