### ISSUE TITLE
asciidoc dependency for building

### ISSUE THREAD

**Issue by kjetillll** [vasi/pixz#74]
The indexing tar and parallel features is really interesting. So I did some initial testing with creating .tar.pixz files and extracting single files.

And it works really well, work correct as far as I could see, about four times faster than tar with regular xz and VERY fast extractions even for large .tar.pixz

Two things though:

1) The asciidoc dependency for ./configure just to check this out seems a bit excessive since apt-get install asciidoc on ubuntu 16.04 requires no less than 1.3 GB of extra disk space and took over 30 min to install on my sluggish line. So maybe there could be some way to test the software without asciidoc since the man page is on github.com anyways.

2) pixz -x dir/some.file.txt < my-regular-non-pixz.tar.xz | tar tv    fails with "tar: This does not look like a tar archive". This was not an indexed tar created by pixz, so an error was to be expected. But the error message text itself stumbled me for a while, because it IS a tar.xz-file, just not one created by pixz. So the error message could be more informative?

I'm not complaining, just suggesting ;-) Anyway, great work!

**Comment by wookietreiber** [comment]
You don't need asciidoc, there is a `--without-manpage` option to `configure`.

**Comment by iavr** [comment]
Thank you for this great work. However, there is no release with the option to not build man page. In fact, this option was added right after the latest release 1.0.6, three years ago. Is there a plan for a new release?

**Comment by vasi** [comment]
Released
