### ISSUE TITLE
does not cross build because of AC_CHECK_FILE use

### ISSUE THREAD

**Issue by bremner** [vasi/pixz#75]
Apparently the use of AC_CHECK_FILE interferes with cross building. Proposed patch attached,

Filed in debian as 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883888
[cross.txt](https://github.com/vasi/pixz/files/1544681/cross.txt)

**Comment by rfmerrill** [comment]
+1 for this

**Comment by thesamesam** [comment]
Fixed by https://github.com/vasi/pixz/commit/4ddfdca8416a008819d08d14d6a6f4796aef7857 / https://github.com/vasi/pixz/pull/88?
