### ISSUE TITLE
-k should be the default

### ISSUE THREAD

**Issue by mirh** [vasi/pixz#87]
Removal of old files should be the optional behavior. It's not nice to discover your files were deleted.

**Comment by vasi** [comment]
Hmm, deleting the original is the default behavior of other compressors, like gzip/bzip2/xz though.

**Comment by mirh** [comment]
I guess it [depends](https://www.reddit.com/r/linux/comments/3cn6k4/why_do_gzip_lzma_and_bzip2_all_delete_their/) on how you see your program going.
