### ISSUE TITLE
build env question not package liblzma

### ISSUE THREAD

**Issue by andotorg** [vasi/pixz#95]
checking for LZMA... no
configure: error: Package requirements (liblzma) were not met:

No package 'liblzma' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LZMA_CFLAGS
and LZMA_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by vasi** [comment]
You need to install the package for your operating system that contains libzma. Eg: on Ubuntu, liblzma-dev.
